name: .NET

on:
  push:
    branches: [ develop-test-unit ]
  pull_request:
    branches: [ develop-test-unit ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup redis
      uses: supercharge/redis-github-action@1.2.0
      with: 
        redis-version: 6

    - name: Install redis cli # so we can test the server
      run: sudo apt-get install -y redis-tools

    - name: Verify that redis is up
      run: redis-cli ping
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
